Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using W2022A6YH.Models;

namespace W2022A6YH.Controllers
{
    public class AlbumController : Controller
    {
        private Manager m = new Manager();
        // GET: Album
        public ActionResult Index()
        {
            return View(m.AlbumGetAll());
        }

        // GET: Album/Details/5

        public ActionResult Details(int? id)
        {
            var Album = m.AlbumGetById(id.GetValueOrDefault());
            if (Album == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(Album);
            }
        }


        [Authorize(Roles = "Clerk")]
        [Route("album/{id}/addtrack")]
        public ActionResult AddTrack(int? id)
        {
            var a = m.AlbumGetById(id.GetValueOrDefault());

            if (a == null)
            {
                return HttpNotFound();
            }
            else
            {
                var form = new TrackAddFormViewModel();
                form.AlbumName = a.Name;
                form.AlbumId = a.Id;
                form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");


                return View(form);
            }
        }

        [Authorize(Roles = "Clerk")]
        [Route("album/{id}/addtrack")]
        [HttpPost]
        public ActionResult AddTrack(TrackAddViewModel newItem)
        {
            if (!ModelState.IsValid)
            {
                var form = new TrackAddFormViewModel();
          
                form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");
                return View(form);
            }

            var addedItem = m.TrackAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("details", "Track", new { id = addedItem.Id });
            }
        }

    }
}

Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using W2022A6YH.Models;

namespace W2022A6YH.Controllers
{
    public class ArtistController : Controller
    {

        private Manager m = new Manager();
        // GET: Artist
        public ActionResult Index()
        {
            return View(m.ArtistGetAll());
        }

        // GET: Artist/Details/5
        public ActionResult Details(int? id)
        {
            var Artist = m.ArtistGetById(id.GetValueOrDefault());
            if (Artist == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(Artist);
            }
        }

        // GET: Artist/Create
        //TODO 01: enable authorize
        [Authorize(Roles = "Executive")]
        public ActionResult Create()
        {
            var form = new ArtistAddFormViewModel();
            form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");
            return View(form);
        }

        // POST: Artist/Create
        [Authorize(Roles = "Executive")]
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(ArtistAddViewModel newItem)
        {
             //var errors = ModelState
             //   .Where(x => x.Value.Errors.Count > 0)
             //   .Select(x => new { x.Key, x.Value.Errors })
             //   .ToArray();

            if (!ModelState.IsValid)
            {
                var form = new ArtistAddFormViewModel();
                form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");
                return View(form);
            }

            var addedItem = m.ArtistAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("details", new { id = addedItem.Id });
            }

        }


        [Authorize(Roles = "Coordinator")]
        [Route("artist/{id}/addalbum")]
        public ActionResult AddAlbum(int? id)
        {
            var a = m.ArtistGetById(id.GetValueOrDefault());

            if (a == null)
            {
                return HttpNotFound();
            }
            else
            {
                var form = new AlbumAddFormViewModel();
                form.ArtistName = a.Name;
                form.ArtistId = a.Id;
                form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");


                return View(form);
            }
        }


        [Authorize(Roles = "Coordinator")]
        [Route("artist/{id}/addalbum")]
        [HttpPost, ValidateInput(false)]
        public ActionResult AddAlbum(AlbumAddViewModel newItem)
        {
            if (!ModelState.IsValid)
            {
                var form = new AlbumAddFormViewModel();
                form.GenreList = new SelectList(m.GenreGetAll(), "Id", "Name");

                return View(form);
            }

            // Process the input
            var addedItem = m.AlbumAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("details", "Album", new { id = addedItem.Id });
            }
        }

        [Authorize(Roles = "Coordinator")]
        [Route("artist/{id}/addmediaitem")]
        public ActionResult AddMediaItem(int? id)
        {
            var o = m.ArtistGetById(id.GetValueOrDefault());

            if (o == null)
            {
                return HttpNotFound();
            }
            else
            {
                var form = new MediaItemAddFormViewModel();
    
                form.ArtistId = o.Id;
                form.ArtistInfo = $"{o.Name}";

                return View(form);
            }
        }

        [HttpPost]
        [Route("artist/{id}/addmediaitem")]
        [Authorize(Roles = "Coordinator")]
        public ActionResult AddMediaItem(int? id, MediaItemAddViewModel newItem)
        {
            if (!ModelState.IsValid && id.GetValueOrDefault() == newItem.ArtistId)
            {
                return View(newItem);
            }

            var addedItem = m.ArtistMediaItemAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("Details", new { id = addedItem.Id });
            }
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Do not modify the meta properties below -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="59180300-7b4e-43b5-93ed-245d085be679" />
	<meta name="application-name" content="2221-W2022A6YH" />
	
    <title>@ViewBag.Title - Music Biz w/ Media Items</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{
        var userAccount = new W2022A6YH.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Biz w/ Media Items", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (userAccount.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Artists", "Index", "Artist")</li>
                        <li>@Html.ActionLink("Albums", "Index", "Album")</li>
                        <li>@Html.ActionLink("Tracks", "Index", "Track")</li>
                    }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; WEB 524 - Winter 2022 - Yiwen Hao@yhao</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>